server:
  port: 9091

spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:test