server:
  port: 9090

spring:
  datasource:
    url: jdbc:h2:~/data/eatgo
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
    secret: 12345678901234567890123456789012
---

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:test